name: MineOnlineBroadcast
version: 1.1.3
description: Lists a server on mineonline.codie.gg/servers
author: codieradical
authors: [Codie]
website: https://mineonline.codie.gg/

main: gg.codie.mineonline.plugin.bukkit.MineOnlineBroadcastPlugin
database: false
depend: []