name: OnlineModeFix
version: 1.1.0
description: Fixes online-mode authentication.
author: craftycodie
authors: [Codie]
website: https://twitter.com/craftycodie

main: gg.codie.mineonline.plugin.bukkit.OnlineModeFixPlugin
database: false
depend: []